name: zkool
description: "Zkool"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.20.10+108

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  convert: ^3.1.1
  cupertino_icons: ^1.0.8
  rlz:
    path: rust_builder
  flutter_rust_bridge: 2.9.0

  logger: ^2.0.2+1
  go_router: ^14.8.1
  flutter_mobx: ^2.0.2
  mobx: ^2.2.1
  gap: ^3.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  freezed_annotation: any

  path_provider: ^2.1.5
  file_picker: ^10.1.2

  collection: ^1.19.1
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1
  animated_reorderable_list: ^1.2.0
  toastification: ^3.0.2

  showcaseview: ^4.0.1

  fixed: ^5.3.3
  timeago: ^3.7.0
  intl: ^0.20.2

  mobile_scanner: ^6.0.7
  qr_flutter: ^4.1.0

  local_auth: ^2.3.0
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  package_info_plus: ^8.3.0
  easy_stepper: ^0.8.5+1
  searchable_listview: ^2.17.3
  flutter_inappwebview: ^6.1.5

  bubble: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.2
  mobx_codegen: ^2.7.0
  freezed: ^2.5.7

  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - misc/icon.png
