name: Build and Release Linux Debian Package on ARM64

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - zkool-v*

permissions:
  contents: write

jobs:
  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Flutter
        run: |
          git clone --depth 1 --branch stable https://github.com/flutter/flutter.git $RUNNER_TEMP/flutter
          echo "$RUNNER_TEMP/flutter/bin" >> $GITHUB_PATH
      - name: Install packages
        run: |
          flutter doctor
          sudo apt-get update
          sudo apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libudev-dev
          dart pub global activate fastforge
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          fastforge package --platform=linux --targets=deb
      - name: Rename deb package
        id: package
        run: |
          PKG_PATH=$(find dist/ -type f -name '*.deb' | head -n 1)
          echo "Found package: $PKG_PATH"
          mv $PKG_PATH .
          BASENAME=$(basename $PKG_PATH ".deb")
          mv $BASENAME.deb $BASENAME-arm64.deb
          echo "PKG_PATH=$BASENAME-arm64.deb" >> $GITHUB_OUTPUT
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.package.outputs.PKG_PATH }}
      - name: Create Release
        if: startsWith(github.ref_name, 'zkool-v')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.PKG_PATH }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
